import {useState} from 'react';
import data from './notion-examples.json';
import WheelPicker from './WheelPicker';
import {localDay,type WorkTask} from '../work-model';
import './work-calendar.css';

type Props={area:'schedule'|'projects';projectView?:string;onCreateDate?:(day:string)=>void;liveTasks?:WorkTask[];onOpenTask?:(task:WorkTask)=>void;onApplyAll?:()=>void;applying?:boolean};
export default function NotionExamples({area,projectView='代辦事項',onCreateDate,liveTasks=[],onOpenTask,onApplyAll,applying=false}:Props){
 const [calendar,setCalendar]=useState(true);const [month,setMonth]=useState('2026-09');const [department,setDepartment]=useState('全部');
 const tasks=data.schedule.filter(t=>department==='全部'||t.department===department);const projects=data.projects.filter(p=>department==='全部'||p.department===department);
 const liveByExample=new Map(liveTasks.filter(t=>t.sourceExampleId).map(t=>[t.sourceExampleId!,t]));
 const allExamples=[...data.schedule,...data.projects];const allApplied=allExamples.every(item=>liveByExample.has(item.id));
 const first=new Date(month+'-01T00:00:00Z');const count=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate();const offset=first.getUTCDay();const today=localDay();
 function changeMonth(delta:number){const date=new Date(first);date.setUTCMonth(date.getUTCMonth()+delta);setMonth(date.toISOString().slice(0,7));}
 function openExample(id:string){const task=liveByExample.get(id);if(task)onOpenTask?.(task);else onApplyAll?.();}
 const colors=['','#b42318','#996500','#15803d'];const tableStyle={width:'100%',borderCollapse:'collapse' as const};
 return <section className="work-module" aria-label={area==='schedule'?'工作排程範例':'專案範例'}>
 <div className="work-example-heading"><p className="work-pilot">Notion 範例資料・{area==='schedule'?'７筆排程':'１３筆專案'}。套用後可點選修改、移除或封存。</p><button className="primary" disabled={applying||allApplied} onClick={onApplyAll}>{applying?'套用中…':allApplied?'全部範例已套用':'套用全部範例'}</button></div>
 {area==='projects'&&<label>部門篩選 <select value={department} onChange={e=>setDepartment(e.target.value)}>{['全部',...new Set([...data.schedule,...data.projects].map(x=>x.department))].map(d=><option key={d}>{d}</option>)}</select></label>}
 {area==='schedule'?<><div className="projects-calendar-shell"><header className="projects-calendar-toolbar"><div><small>WORK CALENDAR</small><WheelPicker kind="month" label="工作月曆月份" value={month} onChange={setMonth}/></div><div className="projects-calendar-actions"><select aria-label="工作月曆部門" value={department} onChange={e=>setDepartment(e.target.value)}>{['全部',...new Set([...data.schedule,...data.projects].map(x=>x.department))].map(d=><option key={d} value={d}>{d==='全部'?'全部部門':d}</option>)}</select><button onClick={()=>setMonth(today.slice(0,7))}>今天</button><button aria-label="工作月曆前一個月" onClick={()=>changeMonth(-1)}>‹</button><button aria-label="工作月曆後一個月" onClick={()=>changeMonth(1)}>›</button><button onClick={()=>setCalendar(!calendar)}>{calendar?'清單':'月曆'}</button></div></header>
 {calendar?<div className="projects-calendar-scroll"><div className="projects-calendar-grid">{['日','一','二','三','四','五','六'].map(d=><div className="projects-weekday" key={d}>{d}</div>)}{Array.from({length:Math.ceil((offset+count)/7)*7},(_,i)=>{const day=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth(),1+i-offset)).toISOString().slice(0,10);const inMonth=day.startsWith(month);return <div key={day} className={'projects-calendar-day'+(!inMonth?' outside':'')+(day===today?' today':'')}>{inMonth&&<><button type="button" className="projects-date-add" aria-label={day+' 新增工作'} onClick={()=>onCreateDate?.(day)}><strong>{Number(day.slice(-2))}</strong><span aria-hidden="true">＋</span></button>{tasks.filter(t=>t.date===day).map(t=><button className="projects-calendar-event sample" key={t.id} style={{borderLeftColor:colors[t.priority]}} onClick={()=>openExample(t.id)}><strong>{t.time} {t.title}</strong><small>{t.supervisor} · {t.status}</small></button>)}</>}</div>})}</div></div>:<div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr>{['工作事項','日期／時間','類型','狀態','主管','部門','優先級'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{tasks.map(t=><tr key={t.id}><td><button className="work-title-button" onClick={()=>openExample(t.id)}>{t.title}</button></td><td>{t.date} {t.time}</td><td>{t.type}</td><td>{t.status}</td><td>{t.supervisor}</td><td>{t.department}</td><td style={{color:colors[t.priority]}}>{t.priority}</td></tr>)}</tbody></table></div>}</div><p>「週末機房備份檢查」原頁分類為重複，週期尚未填寫，因此不自動產生新日期。</p></>:<>
 {projectView==='代辦事項'?<div style={{overflowX:'auto'}}><table style={tableStyle}><thead><tr>{['專案達成目標','主管','優先級','執行狀態','部門','風險','開始日','截止日'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><button className="work-title-button" onClick={()=>openExample(p.id)}>{p.title}</button></td>{[p.supervisor,p.priority,p.status,p.department,p.risk,p.startDate,p.dueDate].map((v,i)=><td key={i} style={{padding:10,borderBottom:'1px solid #e5eaf0'}}>{v}</td>)}</tr>)}</tbody></table></div>:projectView==='管制用甘特圖WBS'?<><p>依專案開始日～截止日顯示；點選專案名稱可修改、移除或封存。</p><div style={{overflowX:'auto'}}><div style={{minWidth:900}}>{projects.map(p=>{const start=Date.parse('2026-07-01'),end=Date.parse('2027-02-01'),left=(Date.parse(p.startDate)-start)/(end-start)*100,width=(Date.parse(p.dueDate)-Date.parse(p.startDate))/(end-start)*100;return <div key={p.id} style={{display:'grid',gridTemplateColumns:'250px 1fr',gap:16,margin:'14px 0'}}><button className="work-title-button" onClick={()=>openExample(p.id)}>{p.title}<br/><small>{p.startDate}～{p.dueDate}</small></button><div style={{background:'#eef2f6',height:28,borderRadius:6}}><button title={p.startDate+'～'+p.dueDate} aria-label={'開啟 '+p.title} onClick={()=>openExample(p.id)} style={{display:'block',border:0,marginLeft:left+'%',width:Math.max(width,1)+'%',height:28,background:p.risk==='高'?'#b45353':'#467bb7',borderRadius:6}}/></div></div>})}<p>時間範圍：2026／07／01～2027／02／01</p></div></div></>:projectView==='檢視／報告用'?<><h3>專案概況</h3><p>共 {projects.length} 件・執行中 {projects.filter(p=>p.status==='執行中').length} 件・未開始 {projects.filter(p=>p.status==='未開始').length} 件・高風險 {projects.filter(p=>p.risk==='高').length} 件</p>{projects.filter(p=>p.risk==='高').map(p=><button className="work-report-example" key={p.id} onClick={()=>openExample(p.id)}>🔴 {p.title}｜{p.supervisor}｜期限 {p.dueDate}</button>)}</>:<p>封存中的正式專案請在下方「正式專案資料與管理工具」查看並恢復。</p>}
 </>}
 </section>;
}
